from utilities.utilities import prepare_reactions
from utilities.utilities import extract_audio, compute_precision_recall, universal_frame_rate, is_close
from utilities.utilities import samples_per_frame, universal_frame_rate, is_close
from utilities.utilities import print_memory_consumption, on_press_key
from utilities.utilities import conversion_audio_sample_rate, conversion_frame_rate